name: Build
on: 
  push:
    paths:
      - Sources/**
      - Tests/**
      - .github/**
  pull_request:
    paths:
      - Sources/**
      - Tests/**
      - .github/**
jobs:
  spm:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: AckeeCZ/load-xcode-version@v1
    - name: SPM build
      run: |
        rm -r StoreKitUserInfo.xcodeproj # otherwise will not use SPM
        set -e pipefail
        xcodebuild -scheme StoreKitUserInfo -destination 'generic/platform=iOS Simulator' | xcpretty
  carthage:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: AckeeCZ/load-xcode-version@v1
    - name: Carthage build
      run: carthage build --platform iOS --use-xcframeworks --no-skip-current