name: Release

on:
  push:
    tags:
    - '*'

jobs:
  carthage:
    name: Upload Carthage binary 
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: AckeeCZ/load-xcode-version@v1
      - name: Build
        run: carthage build --no-skip-current --cache-builds --use-xcframeworks
      - name: Archive
        run: | 
          DST=$PWD
          mkdir -p /tmp/StoreKitUserInfo
          mv Carthage/Build/*.xcframework /tmp/StoreKitUserInfo
          cd /tmp
          zip -r "$DST/"StoreKitUserInfo.xcframework.zip StoreKitUserInfo
      - uses: xresloader/upload-to-github-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: StoreKitUserInfo.xcframework.zip
          tags: true
          draft: false